concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.java.installations.auto-detect=false
    -Dorg.gradle.warning.mode=fail
jobs:
  build:
    name: Release task
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.client_payload.gitRef }}
    - continue-on-error: true
      name: Cache Gradle dependencies
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: '${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Cache Gradle wrappers
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties')
          }}
        path: ~/.gradle/wrapper
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      env:
        OSSRH_PASSWORD: ${{ secrets.ossrhPassword }}
        OSSRH_USERNAME: ${{ secrets.ossrhUsername }}
        SIGNING_GPG_PASSWORD: ${{ secrets.signingPassword }}
        SIGNING_GPG_SECRET_KEY: ${{ secrets.signingKey }}
      name: Publish a release
      run: ./gradlew publish
name: Publish a release to the Maven Central Repository
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
